### ISSUE TITLE
请问您这个训练数据是从那那里来的

### ISSUE THREAD

**Issue by jacobishao** [DamongZ/Road-Detection-with-Tensorflow#1]
我有一个问题：请问您这个训练数据是从那那里来的？

**Comment by DamongZ** [comment]
http://scrd.josemalvarez.net/.

**Comment by jacobishao** [comment]
我这个好像找不到dns服务器

**Comment by jacobishao** [comment]
解析不了这个域名
![image](https://user-images.githubusercontent.com/8140244/27312769-07fdfad8-559d-11e7-9cc5-9da41742598b.png)

**Comment by DamongZ** [comment]
我不知道为什么  现在不能下载了。 如果你需要我可以传到网盘分享给你。

**Comment by DamongZ** [comment]
链接：http://pan.baidu.com/s/1kUTlzhH 
密码：6amn

**Comment by jacobishao** [comment]
多谢多谢

2017-06-25 12:21 GMT+08:00 DamonZhang <notifications@github.com>:
